; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_cache_dir = .pio/build-cache


[env:arduino-esp32]
platform = espressif32
board = nodemcu-32s
build_flags =
	-g
	-DDEBUG_FAUXMO=Serial
	-DDEBUG_FAUXMO_VERBOSE_TCP=0
	-DDEBUG_FAUXMO_VERBOSE_UDP=0

framework = arduino
board_build.filesystem = littlefs
upload_speed = 921600
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
board_build.partitions = src/littlefs_4MB.csv

lib_deps = 
	ESP32Async/AsyncTCP @ ^3.4.10
	bblanchon/ArduinoJson@^6.19.2
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	AsyncMqttClient
	marian-craciunescu/ESP32Ping@^1.7
	arkhipenko/TaskScheduler@^3.6.0
	painlessmesh/painlessMesh@^1.5.0
	adafruit/Adafruit SSD1306@^2.5.4
	vintlabs/FauxmoESP@^3.4
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.3.0
	aircoookie/Espalexa@^2.7.0
	joaolopesf/RemoteDebug@^3.0.5
	arkhipenko/TaskScheduler@^3.7.0
	brawrdon/ESP32 HomeKit SDK for Arduino@^1.1.0
	openenergymonitor/EmonLib@^1.1.0
	alexcajas/EmbeddedMqttBroker@^1.0.3
	alexcajas/WrapperFreeRTOS@^1.0.1
	adafruit/Adafruit ADS1X15@^2.4.0
	robtillaart/ADS1X15@^0.3.9
	paulstoffregen/Time@^1.6.1
	paulstoffregen/OneWire@^2.3.8
	lorol/LittleFS_esp32@^1.0.6

extra_scripts =
	dump_flash.py
    restore_flash.py
    firmware_name.py
